name: JD_Sign_Action

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 20 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: ${{ shshshfpa=99bb1b5c-5db4-d504-c1c9-7c930bd6c9e8-1545272149; shshshfpb=pLKFt4DcHzMuHVzCqsQwXJg%3D%3D; TrackID=1fVDfWFXBJdIVUoKGpeM3RfQoQzljBf1P0HJrVmfgpZWOc2T2lugkhFQDO-5PE6JeLPuxW2rS0xSisVGS9V1zD458dMWYsBBg6JX4eMfzTFM; 3AB9D23F7A4B3C9B=XTTNQBLBAN5JNGDG3ZY2EH2R7F5YORLC6P2RQJWBJ53GARCZJ3ROWX3AQ5IFM3XEFUGQ2GLZAUFZNYB27I3YIALIUY; __jda=122270672.1607575799303485968841.1607575799.1607575799.1607575799.1; __jdv=122270672%7Cdirect%7C-%7Cnone%7C-%7C1607575799308; __jdc=122270672; mba_muid=1607575799303485968841; shshshfp=87bc2cfad254fc68a21d3068c711ec33; shshshsID=dad0f6ffd764d74b0ccca87962e15cc6_1_1607575802312; jcap_dvzw_fp=e336f51ee0a6568f827df0dc26241073$928398104895; TrackerID=9-rvd00Yy42gKqQIo4Zoj-rIQgqen1aj42cBBpUl8aD6cVQrcoIky04Hvho7nRYl-_BCbJEX8Odfjbn1xJIbE0XYe76jDab0mN2UsjUYvG2AkL-s9HqpltKpdpNmTzg-; pt_key=AAJf0akcADDQkR1RkqhQnNjeyVDigkKm-zPCDg3Hy3zAJfQ8zFkYe9QmuWN3hYNxcA_d0FVav5w; pt_pin=jd_7c735ed541808; pt_token=y5h8kp6o; pwdt_id=jd_7c735ed541808; sfstoken=tk01me8d01ceea8sMysxKzMrMngycIMOU8pZpAlAWrAlc0yR7ptUDaTv4e3v3iMao3AGQA6J+wQjQvaNyGkuo/6qKN6e; mobilev=html5; __jdb=122270672.3.1607575799303485968841|1.1607575799; mba_sid=16075757993114410368802232296.3; __jd_ref_cls=Mnpm_ComponentApplied;  }}
  JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}
  PUSH_KEY: ${{ SCU134175T80753e4015c3741de35f60922466d7e75fd1a6d813d3b}}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_sign.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt


